### ISSUE TITLE
UI issue with dropdown window not overlaying correctly

### ISSUE THREAD

**Issue by janpaulus86** [app-generator/django-volt-dashboard-pro2#3] opened 2021-04-27 12:44 UTC
UI issue with dropdown not overlaying correctly when extending past the container border.

System:
- OS: Microsoft Windows 10 Pro Version 10.0.19041 Build 19041
- Browser: Chrome Version 90.0.4430.93 (Official Build) (64-bit)

This is a dropdown window displaying correctly:
![image](https://user-images.githubusercontent.com/46894984/116241301-07d70680-a765-11eb-8125-2fb2e54f3a07.png)

When the dropdown overlay extends past the border, it cuts the dropdown off:
![image](https://user-images.githubusercontent.com/46894984/116241569-4ff62900-a765-11eb-923c-3efdba76b0a7.png)

I've highlighted where the dropdown should overlay:
![image](https://user-images.githubusercontent.com/46894984/116242802-926c3580-a766-11eb-82b6-b51f37f4d65a.png)

Code below:
![image](https://user-images.githubusercontent.com/46894984/116243153-eb3bce00-a766-11eb-8389-85c8f0b207d0.png)

**Comment by zoltanszogyenyi** [comment] 2021-04-27 13:51
Hey @janpaulus86,

Please check if the parent element does not have an `overflow: none;` set. That might be the problem.

We'll also check this out on the master branch.

Thanks,
Zoltan

**Comment by janpaulus86** [comment] 2021-05-06 08:29
Hey @zoltanszogyenyi, 

Thank you, but this does not solve the problem, please see below screenshot with your suggestion. You will notice the dropdown is overflowing now, however the table header is also extending past the boundary. Any further advise?
![image](https://user-images.githubusercontent.com/46894984/117266691-cece1e80-ae55-11eb-880b-19cd6f9e85c2.png)

**Comment by app-generator** [comment] 2021-06-15 07:18
Hello @zoltanszogyenyi, 

Any update on this? Ty!

**Comment by zoltanszogyenyi** [comment] 2021-06-15 08:01
@janpaulus86 @app-generator the issue is solved with the [v1.4.1 update from Volt Pro](https://demo.themesberg.com/volt-pro/pages/users.html).

**Comment by app-generator** [comment] 2021-06-15 09:46
Ty @zoltanszogyenyi

**Comment by app-generator** [comment] 2021-06-30 10:35
Fixed in **v1.0.4**

@janpaulus86 please update.

**Closed as completed by app-generator** 2021-06-30 10:35 UTC
